Create or replace FUNCTION GET_OBSER_MOV_NOV( OBSERVACION_BAJA VARCHAR2 , OBSERVACION_BITACORA VARCHAR2 , OBSERVACION_PERDIDA VARCHAR2 , OBSERVACION_RECUPERACION VARCHAR2 )
RETURN VARCHAR2
IS
CONCAT_RESULT VARCHAR2(100);
BEGIN
    CONCAT_RESULT := '';
    IF OBSERVACION_BAJA IS NOT NULL THEN
      CONCAT_RESULT := CONCAT('OBSERVACIÓN BAJA:' , OBSERVACION_BAJA);    
    END IF;
    
    IF OBSERVACION_BITACORA IS NOT NULL THEN
        IF CONCAT_RESULT = '' THEN
            CONCAT_RESULT := CONCAT('OBSERVACIÓN BITÁCORA:' , OBSERVACION_BITACORA);    
        ELSE
            CONCAT_RESULT := CONCAT(CONCAT_RESULT, CONCAT(' OBSERVACIÓN BITÁCORA:' , OBSERVACION_BITACORA));    
        END IF;      
    END IF;
        
    IF OBSERVACION_PERDIDA IS NOT NULL THEN
        IF CONCAT_RESULT = '' THEN
            CONCAT_RESULT := CONCAT('OBSERVACIÓN PERDIDA:' , OBSERVACION_PERDIDA);    
        ELSE
            CONCAT_RESULT := CONCAT(CONCAT_RESULT, CONCAT(' OBSERVACIÓN PERDIDA:' , OBSERVACION_PERDIDA));    
        END IF;      
    END IF;
    
    IF OBSERVACION_RECUPERACION IS NOT NULL THEN
        IF CONCAT_RESULT = '' THEN
            CONCAT_RESULT := CONCAT('OBSERVACIÓN RECUPERACIÓN:' , OBSERVACION_RECUPERACION);    
        ELSE
            CONCAT_RESULT := CONCAT(CONCAT_RESULT, CONCAT(', OBSERVACIÓN RECUPERACIÓN:' , OBSERVACION_RECUPERACION));    
        END IF;
    END IF;
    RETURN  CONCAT_RESULT;
END RPT_HIST_NOVE_MOVI_GET_OBSERVACIÓN_NOVEDAD;