 LEFT JOIN (
        SELECT Mi.ID AS MANTENIMIENTO_ID, MDi2.MANT_DOCUMENTO_ID
            FROM  MANTENIMIENTO Mi
            INNER JOIN (
                SELECT MDi.MANTENIMIENTO_ID, max(MDi.ID) AS MANT_DOCUMENTO_ID
                FROM MANTENIMIENTO_DOCUMENTO MDi
                group by MDi.MANTENIMIENTO_ID
            ) MDi2 on Mi.ID = MDi2.MANTENIMIENTO_ID
            --PENDIENTE FITRO TRANSICION O DOCUMENTO
        ) MD on M.ID = MD.MANTENIMIENTO_ID
