-- Desde un objetoBD
INSERT INTO LISTA (ID,ACTIVO,DESCRIPCION,NOMBRE) SELECT ID,ACTIVO,DESCRIPCION,NOMBRE FROM SIGMA_GEO.LISTA;

-- Usando items por registros con un solo Insert
INSERT ALL
INTO LISTA (ID,ACTIVO,DESCRIPCION,NOMBRE) values ('16','1','TAB_MANTENIMIENTO_VIAL_ID_TIPO_MALLA','MEJORAMIENTO_TIPO_MALLA')
INTO LISTA (ID,ACTIVO,DESCRIPCION,NOMBRE) values ('17','1','TAB_MANTENIMIENTO_VIAL_ID_TIPO_IMPACTO_SOCIAL','MEJORAMIENTO_IMPACTO_SOCIAL')
INTO LISTA (ID,ACTIVO,DESCRIPCION,NOMBRE) values ('16','1','TAB_MANTENIMIENTO_VIAL_ID_TIPO_MALLA','MEJORAMIENTO_TIPO_MALLA')
INTO PERMISO (ID,ACTIVO,NOMBRE) values ('200','1','MEJORAMIENTO_DIAGNOSTICOFALLA_LIST')
INTO PERMISO (ID,ACTIVO,NOMBRE) values ('201','1','MEJORAMIENTO_DIAGNOSTICOFALLA_EXPORT')
SELECT * FROM dual;
